format = """\
  $username\
  $hostname\
  $kubernetes\
  $directory\
  ${custom.arch}\
  $aws\
  $docker_context\
  $package\
  $dotnet\
  $elixir\
  $elm\
  $erlang\
  $golang\
  $java\
  $julia\
  $nim\
  $nodejs\
  $ocaml\
  $php\
  $purescript\
  $python\
  $ruby\
  $rust\
  $terraform\
  $zig\
  $nix_shell\
  $conda\
  $memory_usage\
  $crystal\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  ${custom.time_since_commit}\
  $env_var\
  $hg_branch\
  $cmd_duration\
  $line_break\
  $jobs\
  $battery\
  $time\
  $character\
  """

[character]
success_symbol ="[](bold green)"
error_symbol ="[](bold red)"

[directory]
truncate_to_repo = false

[time]
disabled = false
use_12hr = true
time_format = "%r"
style = "bold cyan"

[aws]
style = "bold blue"
symbol = " "

[terraform]
disabled = true
symbol = "🏎💨 "
show_version = false

[git_branch]
symbol = " "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
ahead = "🚀"
untracked = "🤷"
stashed = "📦"
modified = "📝"
deleted = "🗑"

[git_commit]
style = "bold purple"
only_detached = false

[package]
disabled = true

[battery]
disabled = false

[[battery.display]]
threshold = 100
style = "bold green"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[custom.time_since_commit]
command = "~/.dotfiles/starship/time-since-commit.zsh"
when = """ git rev-parse --git-dir > /dev/null 2>&1 """
format = "[$symbol$output ago ]($style)"

[custom.arch]
command = "arch"
when = """ echo 0 """
format = "[on $symbol $output ]($style)"
symbol = ""

[env_var]
variable = 'AWS_PROFILE'
style = "bold yellow"
format = " [$env_value]($style) "
