---
- name: Tap homebrew repos
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/dupes
  tags:
    - homebrew

- name: Install command line tools
  homebrew: name={{ item }} state=present
  with_items:
    - openssl
    - ag
    - git
    - vim
    - z
    - curl
    - wget
    - jq
    - cowsay
    - optipng
    - tmux
    - git-flow-avh
    - git-extras
    - heroku-toolbelt
    - terraform
    - packer
    - coreutils
    - mongodb
    - reattach-to-user-namespace
    - rename
    - thefuck
    - neovim/neovim/neovim
    - hub
    - ngrok
    - mas
  tags:
    - homebrew

- name: Install Ruby Gems
  shell: "{{ rvm }} all do gem install {{ item }}"
  #gem: name={{ item }} state=present
  sudo: false
  with_items:
    - tmuxinator
  tags:
    - ruby

- name: Install Node modules
  npm: name={{ item }} state=present global=yes
  with_items:
    - webpack
    - webpack-dev-server
    - standard
    - standard-format
    - eslint
    - yarn
  tags:
    - node

- name: Install pip dependencies
  pip: name={{ item }} state=present global=yes
  with_items:
    - neovim
