---
- name: Tap homebrew repos
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/dupes
  tags:
    - homebrew

- name: Install command line tools
  homebrew: name={{ item }} state=present
  with_items:
    - openssl
    - ag
    - git
    - vim
    - z
    - curl
    - wget
    - jq
    - cowsay
    - optipng
    - composer
    - tmux
    - git-flow-avh
    - git-extras
    - heroku-toolbelt
    - terraform
    - packer
    - otto
    - coreutils
    - mongodb
    - brew install reattach-to-user-namespace
  tags:
    - homebrew

- name: Install Ruby Gems
  shell: "{{ rvm }} all do gem install {{ item }}"
  #gem: name={{ item }} state=present
  sudo: false
  with_items:
    - tmuxinator
  tags:
    - ruby

- name: Install Node modules
  npm: name={{ item }} state=present global=yes
  with_items:
    - grunt-cli
    - bower
    - babel
    - babel-core
    - webpack
    - webpack-dev-server
    - redux-cli
    - standard
    - standard-format
  tags:
    - node
