---
- name: Tap homebrew repos
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/dupes
  tags:
    - homebrew

- name: Install command line tools
  homebrew: name={{ item }} state=present
  with_items:
    - ack
    - asciinema
    - awscli
    - cask
    - cli53
    - homebrew/php/composer
    - coreutils
    - cowsay
    - curl
    - diff-so-fancy
    - dnsmasq
    - ffmpeg
    - gcc@4.9
    - git
    - git-crypt
    - git-extras
    - git-flow-avh
    - gnu-sed
    - graphviz
    - heroku
    - highlight
    - htop
    - hub
    - imagemagick
    - jq
    - mas
    - neovim/neovim/neovim
    - openssl
    - packer
    - parallel
    - reattach-to-user-namespace
    - rename
    - ripgrep
    - s3cmd
    - saltstack
    - shellcheck
    - siege
    - snappy
    - terminal-notifier
    - terraform
    - the_silver_searcher
    - thefuck
    - tmux
    - watch
    - wget
    - yarn
    - z
    - zsh


  tags:
    - homebrew

- name: Install Ruby Gems
  shell: "{{ rvm }} all do gem install {{ item }}"
  #gem: name={{ item }} state=present
  sudo: false
  with_items:
    - tmuxinator
  tags:
    - ruby

- name: Install pip dependencies
  pip: name={{ item }} state=present global=yes
  with_items:
    - neovim
