---
- name: Tap homebrew repos
  homebrew_tap:
    name:
      - aws/tap
      - moncho/dry
      - moncho/dry
      - dwarvesf/homebrew-tap
    state: present
  tags:
    - homebrew

- name: Install command line tools
  homebrew:
    state: present
    name:
      - asciinema
      - autoconf
      - automake
      - aws-sam-cli
      - bandwhich
      - bat
      - cask
      - composer
      - coreutils
      - curl
      - diff-so-fancy
      - dnsmasq
      - dry
      - exa
      - ffmpeg
      - fish
      - fzf
      - gcc@4.9
      - git
      - git-crypt
      - git-delta
      - git-extras
      - git-flow-avh
      - gnu-tar
      - gnu-sed
      - gawk
      - gnutls
      - gnu-indent
      - gnu-getopt
      - grep
      - graphviz
      - highlight
      - htop
      - hub
      - imagemagick
      - jq
      - libtool
      - libxslt
      - libyaml
      - mas
      - nnn
      - neovim/neovim/neovim
      - openssl
      - packer
      - parallel
      - readline
      - reattach-to-user-namespace
      - rename
      - ripgrep
      - s3cmd
      - saltstack
      - shellcheck
      - siege
      - snappy
      - starship
      - terminal-notifier
      - tfenv
      - terraform_landscape
      - tldr
      - thefuck
      - tmux
      - unixodbc
      - vimmotion
      - watch
      - wget
      - yarn
      - yamllint
      - zsh
      - zsh-completions

  tags:
    - homebrew

# install zoxide instead of z
# curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ajeetdsouza/zoxide/master/install.sh | sh

- name: Install python dependencies
  pip: name={{ item }} state=present executable=/usr/local/bin/pip3
  with_items:
    - awscli
    - neovim

  tags:
    - pip
    - python

- name: Install global nodejs dependencies
  npm:
    state: present
    global: yes
    name:
      - n
      - neovim
  tags:
    - nodejs
    - npm
