---
- name: Tap homebrew repos
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/cask-fonts
  tags:
    - homebrew

- name: Install applications
  homebrew_cask:
    state: present
    name:
#      - 1password
      - a-better-finder-rename
      - alfred
      - bartender
      - bettertouchtool
      - dash
      - docker
      - font-fira-code
      - font-source-code-pro
      - firefox
      - google-chrome
      - google-drive-file-stream
      - gpg-suite
      - istat-menus
      - iterm2
      - karabiner-elements
      - keybase
      - ngrok
      - pocket-casts
      - qlcolorcode
      - qlimagesize
      - qlmarkdown
      - qlprettypatch
      - qlstephen
      - quicklook-csv
      - quicklook-json
      - rescuetime
      - sequel-pro
      - slack
      - spotify
      - station
      - steam
      - sublime-text
      - suspicious-package
      - the-unarchiver
      - unity-web-player
      - vagrant
      - virtualbox
      - vlc
      - webpquicklook
