---
- name: Install applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    - a-better-finder-rename
    - adobe-reader
    - alfred
    - audacity
    - bartender
    - bettertouchtool
    - betterzipql
    - calibre
    - colloquy
    - dash
    - docker
    - dropbox
    - dropbox-encore
    - evernote
    - firefox
    - franz
    - google-chrome
    - google-drive
    - gpgtools
    - hammerspoon
    - istat-menus
    - karabiner-elements
    - keybase
    - mindnode-pro
    - ngrok
    - postico
    - qlcolorcode
    - qlimagesize
    - qlmarkdown
    - qlprettypatch
    - qlstephen
    - quicklook-csv
    - quicklook-json
    - rescuetime
    - sequel-pro
    - sketch
    - skype
    - slack
    - steam
    - sublime-text
    - suspicious-package
    - the-unarchiver
    - unity-web-player
    - vagrant
    - virtualbox
    - vlc
    - webpquicklook
