---
- name: Install applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    - alfred
    - a-better-finder-rename
    - bettertouchtool
    - bartender
    - codekit
    - dash
    - dropbox
    - dropbox-encore
    - evernote
    - forklift
    - github-desktop
    - google-chrome
    - google-drive
    - gpgtools
    - istat-menus
    - mindnode-pro
    - rescuetime
    - sketch
    - skype
    - slicy
    - steam
    - sublime-text
    - the-unarchiver
    #- unity
    - unity-web-player
    - virtualbox
    - vagrant
    - vlc
    - qlcolorcode
    - qlstephen
    - qlmarkdown
    - quicklook-json
    - qlprettypatch
    - quicklook-csv
    - betterzipql
    - qlimagesize
    - webpquicklook
    - suspicious-package
    - sequel-pro
