---
- name: Install applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    - alfred
    - a-better-finder-rename
    - bettertouchtool
    - bartender
    - carbon-copy-cloner
    - codekit
    - dash
    - dropbox
    - dropbox-encore
    - evernote
    - forklift
    - github-desktop
    - google-chrome
    - google-drive
    - gpgtools
    - istat-menus
    - kaleidoscope
    - mindnode-pro
    - private-internet-access
    - rescuetime
    - sketch
    - skype
    - slack
    - slicy
    - steam
    - sublime-text
    - the-unarchiver
    #- unity
    - unity-web-player
    - virtualbox
    - vagrant
    - vlc
